# Generated by Django 4.2 on 2026-05-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('genero', models.CharField(choices=[('A', 'Accion'), ('H', 'Horror'), ('T', 'Thriller'), ('C', 'Comedia')], max_length=30)),
                ('director', models.CharField(max_length=100)),
                ('anio', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_peliculas/')),
            ],
        ),
    ]
